// server/routes/reports.js
const express = require("express");
const pool = require("../db");
const router = express.Router();
const requireAuth = require("../middleware/requireAuth");
const PDFDocument = require("pdfkit");

// Simple in-memory cache with TTL
const cache = new Map();
function cacheSet(key, value, ttlMs = 30 * 1000) {
  cache.set(key, { value, expires: Date.now() + ttlMs });
  setTimeout(() => {
    const v = cache.get(key);
    if (v && v.expires <= Date.now()) cache.delete(key);
  }, ttlMs + 50);
}
function cacheGet(key) {
  const v = cache.get(key);
  if (!v) return null;
  if (v.expires <= Date.now()) {
    cache.delete(key);
    return null;
  }
  return v.value;
}

// tolerant param parser
function safeParseParams(raw) {
  if (!raw) return {};
  if (typeof raw === "object") return raw;
  try {
    return JSON.parse(raw);
  } catch (e) {
    try {
      // try single-quote -> double-quote fix
      return JSON.parse(String(raw).replace(/'/g, '"'));
    } catch (e2) {
      return { raw: String(raw) };
    }
  }
}

/**
 * POST /api/reports/generate
 * body: { report_type: string, parameters: object }
 */
router.post("/generate", requireAuth(["HR", "MANAGER"]), async (req, res) => {
  const { report_type, parameters } = req.body || {};
  if (!report_type) return res.status(400).json({ error: "report_type required" });

  try {
    const generated_by = req.user && req.user.user_id ? req.user.user_id : null;
    const [r] = await pool.query(
      "INSERT INTO Report (report_type, parameters, generated_by) VALUES (?, ?, ?)",
      [report_type, JSON.stringify(parameters || {}), generated_by]
    );
    const [rows] = await pool.query("SELECT * FROM Report WHERE report_id = ?", [r.insertId]);
    res.status(201).json(rows[0]);
  } catch (err) {
    console.error("POST /api/reports/generate error:", err);
    res.status(500).json({ error: "server error" });
  }
});

/**
 * GET /api/reports
 * list recent reports
 */
router.get("/", requireAuth(["HR", "MANAGER"]), async (req, res) => {
  try {
    const [rows] = await pool.query(
      "SELECT r.*, u.username FROM Report r LEFT JOIN `User` u ON u.user_id = r.generated_by ORDER BY r.generated_at DESC LIMIT 50"
    );
    res.json(rows);
  } catch (err) {
    console.error("GET /api/reports error:", err);
    res.status(500).json({ error: "server error" });
  }
});

/**
 * GET /api/reports/:id
 * single report meta
 */
router.get("/:id(\\d+)", requireAuth(["HR", "MANAGER"]), async (req, res) => {
  const id = Number(req.params.id);
  try {
    const [rows] = await pool.query(
      "SELECT r.*, u.username FROM Report r LEFT JOIN `User` u ON u.user_id = r.generated_by WHERE r.report_id = ?",
      [id]
    );
    if (!rows.length) return res.status(404).json({ error: "not found" });
    res.json(rows[0]);
  } catch (err) {
    console.error("GET /api/reports/:id error:", err);
    res.status(500).json({ error: "server error" });
  }
});

/**
 * GET /api/reports/:id/download
 * generate a PDF for a report (inline)
 */
router.get("/:id(\\d+)/download", requireAuth(["HR", "MANAGER"]), async (req, res) => {
  const id = Number(req.params.id);
  try {
    const [rows] = await pool.query(
      "SELECT r.*, u.username FROM Report r LEFT JOIN `User` u ON u.user_id = r.generated_by WHERE r.report_id = ?",
      [id]
    );
    if (!rows.length) return res.status(404).json({ error: "not found" });

    const report = rows[0];
    const params = safeParseParams(report.parameters);

    const filename = `report-${report.report_id}.pdf`;
    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", `inline; filename="${filename}"`);

    const doc = new PDFDocument({ size: "A4", margin: 48 });
    doc.pipe(res);

    // Title + meta
    doc.fontSize(18).font("Helvetica-Bold").text(`Report: ${report.report_type}`, { align: "left" });
    doc.moveDown(0.25);
    doc.fontSize(10).font("Helvetica").text(`Report ID: ${report.report_id}`);
    doc.text(`Generated by: ${report.username || "system"}`);
    doc.text(`Generated at: ${new Date(report.generated_at).toLocaleString()}`);
    doc.moveDown(0.5);

    // Parameters (human friendly)
    doc.font("Helvetica-Bold").fontSize(11).text("Parameters:");
    doc.font("Helvetica").fontSize(10);
    const prettyParams = (() => {
      const from = params.from || params.start || null;
      const to = params.to || params.end || null;
      if (from && to) return `From: ${from}  →  To: ${to}`;
      if (from) return `From: ${from}`;
      if (to) return `To: ${to}`;
      if (params.month) return `Month: ${params.month}`;
      if (params.year) return `Year: ${params.year}`;
      const entries = Object.entries(params).filter(([k, v]) => v !== null && v !== undefined && (typeof v === "string" || typeof v === "number"));
      if (entries.length) return entries.map(([k, v]) => `${k}: ${v}`).join("   ");
      return "No parameters";
    })();
    doc.text(prettyParams);
    doc.moveDown(0.8);

    // If attendance summary, include a simple tabular section
    if (String(report.report_type).toUpperCase() === "ATTENDANCE_SUMMARY") {
      const fromDate = params.from || params.start || null;
      const toDate = params.to || params.end || null;

      let q = `
        SELECT a.date, a.check_in, a.check_out, a.status,
               e.employee_id, e.employee_code, u.full_name, d.name AS department_name
        FROM Attendance a
        LEFT JOIN Employee e ON e.employee_id = a.employee_id
        LEFT JOIN \`User\` u ON u.user_id = e.user_id
        LEFT JOIN Department d ON d.department_id = e.department_id
      `;
      const where = [];
      const qParams = [];
      if (fromDate) {
        where.push("a.date >= ?");
        qParams.push(fromDate);
      }
      if (toDate) {
        where.push("a.date <= ?");
        qParams.push(toDate);
      }
      if (where.length) q += " WHERE " + where.join(" AND ");
      q += " ORDER BY a.date ASC, u.full_name ASC LIMIT 1000"; // safety cap

      const [attRows] = await pool.query(q, qParams);

      doc.font("Helvetica-Bold").fontSize(12).text("Attendance Summary", { underline: true });
      doc.moveDown(0.3);

      // header row
      doc.fontSize(9).font("Helvetica-Bold");
      doc.text("Date", { continued: true, width: 80 });
      doc.text("Code", { continued: true, width: 80 });
      doc.text("Name", { continued: true, width: 160 });
      doc.text("Dept", { continued: true, width: 100 });
      doc.text("In", { continued: true, width: 60 });
      doc.text("Out", { continued: true, width: 60 });
      doc.text("Status");
      doc.moveDown(0.3);

      doc.font("Helvetica").fontSize(9);
      let present = 0,
        absent = 0,
        late = 0;
      for (const r of attRows) {
        const dateStr = r.date ? new Date(r.date).toLocaleDateString() : "";
        const checkIn = r.check_in ? new Date(r.check_in).toLocaleTimeString() : "";
        const checkOut = r.check_out ? new Date(r.check_out).toLocaleTimeString() : "";
        const status = r.status || "";

        if (status === "PRESENT") present++;
        else if (status === "ABSENT") absent++;
        else if (status === "LATE") late++;

        doc.text(dateStr, { continued: true, width: 80 });
        doc.text(r.employee_code || "", { continued: true, width: 80 });
        doc.text(r.full_name || "", { continued: true, width: 160 });
        doc.text(r.department_name || "", { continued: true, width: 100 });
        doc.text(checkIn, { continued: true, width: 60 });
        doc.text(checkOut, { continued: true, width: 60 });
        doc.text(status);

        // handle page overflow
        if (doc.y > doc.page.height - 80) {
          doc.addPage();
          doc.font("Helvetica").fontSize(9);
        }
      }

      doc.moveDown(0.6);
      doc.font("Helvetica-Bold").fontSize(10).text(`Totals: Present: ${present}   Absent: ${absent}   Late: ${late}`);
      doc.moveDown(0.5);
    } else {
      // fallback/placeholder content for other report types
      doc.font("Helvetica-Bold").fontSize(12).text("Report Contents:");
      doc.moveDown(0.2);
      doc.font("Helvetica").fontSize(10).text(
        "This PDF contains a system-generated summary. To produce business-ready tables or charts for this report type, extend this endpoint with the appropriate queries and layout."
      );
    }

    doc.moveDown(1);
    doc.fontSize(9).fillColor("gray").text("Generated by HR system", { align: "center" });

    doc.end();
  } catch (err) {
    console.error("GET /api/reports/:id/download error:", err);
    if (!res.headersSent) res.status(500).json({ error: "server error" });
    else res.end();
  }
});

/**
 * GET /api/reports/summary/overview
 * optional query: from, to (YYYY-MM-DD)
 */
router.get("/summary/overview", requireAuth(["HR", "MANAGER"]), async (req, res) => {
  const from = req.query.from || null;
  const to = req.query.to || null;
  const cacheKey = `overview:${from || ""}:${to || ""}`;
  try {
    const cached = cacheGet(cacheKey);
    if (cached) return res.json(cached);

    const where = [];
    const params = [];
    if (from) {
      where.push("date >= ?");
      params.push(from);
    }
    if (to) {
      where.push("date <= ?");
      params.push(to);
    }
    const whereSql = where.length ? "WHERE " + where.join(" AND ") : "";

    const q = `
      SELECT
        SUM(status = 'PRESENT') AS present,
        SUM(status = 'ABSENT') AS absent,
        SUM(status = 'LATE') AS late,
        COALESCE(SUM(status = 'PRESENT') / NULLIF(COUNT(*),0) * 100, 0) AS attendance_rate
      FROM Attendance
      ${whereSql}
    `;
    const [rows] = await pool.query(q, params);
    const out = rows[0] || { present: 0, absent: 0, late: 0, attendance_rate: 0 };
    const result = {
      present: Number(out.present || 0),
      absent: Number(out.absent || 0),
      late: Number(out.late || 0),
      attendance_rate: out.attendance_rate ? Number(out.attendance_rate) : 0,
    };
    cacheSet(cacheKey, result, 20 * 1000);
    res.json(result);
  } catch (err) {
    console.error("GET /summary/overview error:", err);
    res.status(500).json({ error: "server error" });
  }
});

/**
 * GET /api/reports/summary/monthly?year=2025&department_id=3
 * returns labels: [Jan..Dec], present[], absent[], late[]
 */
router.get("/summary/monthly", requireAuth(["HR", "MANAGER"]), async (req, res) => {
  const year = Number(req.query.year) || new Date().getFullYear();
  const department_id = req.query.department_id ? Number(req.query.department_id) : null;
  const cacheKey = `monthly:${year}:${department_id || "all"}`;

  try {
    const cached = cacheGet(cacheKey);
    if (cached) return res.json(cached);

    const params = [year];
    let deptJoin = "";
    let deptWhere = "";
    if (department_id && Number.isFinite(department_id)) {
      deptJoin = " LEFT JOIN Employee e2 ON e2.employee_id = a.employee_id";
      deptWhere = " AND e2.department_id = ?";
      params.push(department_id);
    }

    const q = `
      SELECT MONTH(a.date) AS m,
        SUM(a.status = 'PRESENT') AS present,
        SUM(a.status = 'ABSENT') AS absent,
        SUM(a.status = 'LATE') AS late
      FROM Attendance a
      ${deptJoin}
      WHERE YEAR(a.date) = ? ${deptWhere}
      GROUP BY MONTH(a.date)
      ORDER BY MONTH(a.date)
    `;
    const [rows] = await pool.query(q, params);

    const labels = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];
    const present = Array(12).fill(0), absent = Array(12).fill(0), late = Array(12).fill(0);
    rows.forEach((r) => {
      const idx = (Number(r.m) || 1) - 1;
      if (idx >= 0 && idx < 12) {
        present[idx] = Number(r.present || 0);
        absent[idx] = Number(r.absent || 0);
        late[idx] = Number(r.late || 0);
      }
    });

    const out = { labels, present, absent, late };
    cacheSet(cacheKey, out, 60 * 1000);
    res.json(out);
  } catch (err) {
    console.error("GET /summary/monthly error:", err);
    res.status(500).json({ error: "server error" });
  }
});

/**
 * GET /api/reports/summary/yearly?years=2023,2024,2025
 * returns arrays for each supplied year
 */
router.get("/summary/yearly", requireAuth(["HR", "MANAGER"]), async (req, res) => {
  const yearsParam = req.query.years;
  let years = [];
  if (yearsParam) {
    years = String(yearsParam).split(",").map((y) => Number(y)).filter(Boolean);
  }
  if (!years.length) {
    const thisYear = new Date().getFullYear();
    years = [thisYear - 2, thisYear - 1, thisYear];
  }
  const cacheKey = `yearly:${years.join(",")}`;

  try {
    const cached = cacheGet(cacheKey);
    if (cached) return res.json(cached);

    const labels = [];
    const present = [], absent = [], late = [];
    for (const y of years) {
      const [rows] = await pool.query(
        `
        SELECT
          SUM(status = 'PRESENT') AS present,
          SUM(status = 'ABSENT') AS absent,
          SUM(status = 'LATE') AS late
        FROM Attendance
        WHERE YEAR(date) = ?
      `,
        [y]
      );
      const r = rows[0] || {};
      labels.push(String(y));
      present.push(Number(r.present || 0));
      absent.push(Number(r.absent || 0));
      late.push(Number(r.late || 0));
    }
    const out = { labels, present, absent, late };
    cacheSet(cacheKey, out, 60 * 1000);
    res.json(out);
  } catch (err) {
    console.error("GET /summary/yearly error:", err);
    res.status(500).json({ error: "server error" });
  }
});

/**
 * GET /api/reports/summary/departments?year=2025
 * returns counts grouped by department
 */
router.get("/summary/departments", requireAuth(["HR", "MANAGER"]), async (req, res) => {
  const year = Number(req.query.year) || new Date().getFullYear();
  const cacheKey = `dept:${year}`;

  try {
    const cached = cacheGet(cacheKey);
    if (cached) return res.json(cached);

    const [rows] = await pool.query(
      `
      SELECT d.name AS department,
        SUM(a.status = 'PRESENT') AS present,
        SUM(a.status = 'ABSENT') AS absent,
        SUM(a.status = 'LATE') AS late
      FROM Attendance a
      JOIN Employee e ON e.employee_id = a.employee_id
      JOIN Department d ON d.department_id = e.department_id
      WHERE YEAR(a.date) = ?
      GROUP BY d.department_id
      ORDER BY d.name
    `,
      [year]
    );

    const labels = [], present = [], absent = [], late = [];
    rows.forEach((r) => {
      labels.push(r.department);
      present.push(Number(r.present || 0));
      absent.push(Number(r.absent || 0));
      late.push(Number(r.late || 0));
    });

    const out = { labels, present, absent, late };
    cacheSet(cacheKey, out, 60 * 1000);
    res.json(out);
  } catch (err) {
    console.error("GET /summary/departments error:", err);
    res.status(500).json({ error: "server error" });
  }
});

module.exports = router;
